absolute_path: /home/yourfirstname.yourlastname/experiment/gpt2_distillation_products/output_dir_save_gpt2_distillation_products_embedding
use_lightning_checkpoint: false
lm_name: gpt2
dataset_name: ogbn-products
only_title: False
noisy: False
device: cuda
path_to_model: /home/yourfirstname.yourlastname/experiment/gpt2_distillation_products/tune_hyperparameters_gpt2_products/model_checkpoints/lr_0.0002187023895664096
path_to_save_file: gpt2_distillation_products_embedding.npy