absolute_path: /home/yourfirstname.yourlastname/experiment/save_noisy_standard_embeddings/
lm_name: bert-base-uncased
use_standard: true
dataset_name: ogbn-products
noisy: true
path_to_save_file: bert_products_noisy_standard_embedding.npy