absolute_path: /home/yourfirstname.yourlastname/experiment/save_noisy_standard_embeddings/
lm_name: gpt2
use_standard: true
dataset_name: ogbn-arxiv
noisy: true
path_to_save_file: gpt2_arxiv_noisy_standard_embedding.npy