absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/output_dir_mlp_baseline_bert_arxiv

dataset_name: ogbn-arxiv

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/saved_embeddings_dir/best_model_lr_1.2452967354253948e-05.npy
path_to_embeddings: /home/yourfirstname.yourlastname/experiment/repeat_bert_distillation_for_all_layers/output_dir_distill_embedding_repeat_bert_distillation_for_all_layers

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 2
save_model_small: false
path_to_pretrained_classifier: './saved/classifier_with_standard_bert.pth'