absolute_path: /home/yourfirstname.yourlastname/experiment/bert_noisy_products/output_dir_bert_noisy_products_experiment
model_name: bert-base-uncased
dataset_name: ogbn-products
only_title: False
noisy: True
path_to_teacher_embedding: /home/yourfirstname.yourlastname/experiment/bert_noisy_products/output_dir_save_bert_noisy_products_embedding/bert_noisy_products_embedding.npy
min_layers: 1
max_layers: 9