absolute_path: /home/yourfirstname.yourlastname/experiment/gpt2_noisy_arxiv/output_dir_distill_embedding_gpt2_noisy_arxiv
file_path: /home/yourfirstname.yourlastname/experiment/gpt2_noisy_arxiv/output_dir_gpt2_noisy_arxiv_experiment/model_checkpoints_test
model_name: gpt2
dataset_name: ogbn-arxiv
only_title: False
noisy: True