absolute_path: /home/yourfirstname.yourlastname/experiment/gpt2_only_title/output_dir_distill_embedding_gpt2_only_title
file_path: /Users/yourfirstnameyourlastname/Desktop/gpt2_only_title/output_dir_gpt2_distillation_only_title_experiment/model_checkpoints_test
model_name: gpt2
dataset_name: ogbn-arxiv
only_title: True