absolute_path: /home/yourfirstname.yourlastname/experiment/distilbert_noisy_products/performance_on_clean_text/output_dir_distill_embedding_distilbert_noisy_products_clean
file_path: /home/yourfirstname.yourlastname/experiment/distilbert_noisy_products/output_dir_distilbert_noisy_products_experiment/model_checkpoints_test
model_name: distilbert-base-uncased
dataset_name: ogbn-products
only_title: False
noisy: False