absolute_path: /home/yourfirstname.yourlastname/experiment/distilbert_noisy_products/performance_on_clean_text/output_dir_save_distilbert_noisy_products_clean_embedding
use_lightning_checkpoint: false
lm_name: distilbert-base-uncased
dataset_name: ogbn-products
only_title: False
noisy: False
device: cuda
path_to_model: /home/yourfirstname.yourlastname/experiment/distilbert_noisy_products/output_dir_train_robust_lm_distilbert_noisy_products/model_checkpoints/robust_distilbert-base-uncased_for_noisy_ogbn-products_max_epoch_2
path_to_save_file: distilbert_noisy_products_clean_embedding.npy