absolute_path: /home/yourfirstname.yourlastname/experiment/distilbert_noisy_arxiv/performance_on_clean_text/output_dir_distill_embedding_distilbert_noisy_arxiv
file_path: /home/yourfirstname.yourlastname/experiment/distilbert_noisy_arxiv/output_dir_distilbert_noisy_arxiv_experiment/model_checkpoints_test
model_name: distilbert-base-uncased
dataset_name: ogbn-arxiv
only_title: False
noisy: False