absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/output_dir_mlp_baseline__bert_arxiv_only_title

dataset_name: ogbn-arxiv

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/bert_only_title/output_dir_save_bert_only_title_embedding/bert_only_title_embedding.npy
path_to_embeddings: /home/yourfirstname.yourlastname/experiment/bert_only_title/output_dir_distill_embedding_bert_only_title

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 2
save_model_small: false
path_to_pretrained_classifier: './saved/classifier_with_standard_bert.pth'