absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/output_dir_mlp_baseline_gpt2_products

dataset_name: ogbn-products

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/gpt2_distillation_products/output_dir_save_gpt2_distillation_products_embedding/gpt2_distillation_products_embedding.npy
path_to_embeddings: /home/yourfirstname.yourlastname/experiment/gpt2_distillation_products/output_dir_distill_embedding_gpt2_distillation_products

batch_size: 16
learning_rate: 4.986838925488867e-05
max_epoch: 2
save_model_small: false
path_to_pretrained_classifier: /home/yourfirstname.yourlastname/experiment/classifier_with_standard/classifier_with_standard_gpt2_products/model_checkpoints/classifier_with_standard_gpt2_products.pth