absolute_path: ./distilbert_noisy_arxiv/output_dir_train_robust_lm_distilbert_noisy_arxiv
model_name: distilbert-base-uncased
dataset_name: ogbn-arxiv
path_to_pretrained_classifier: ./saved/classifier_with_standard_bert.pth
dropout_rate: 0.1
learning_rate: 1.2755255563146731e-05
save_model_small: true
max_epoch: 2
custom_name: robust_distilbert-base-uncased_for_noisy_ogbn-arxiv_max_epoch_2