absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/trained_on_clean_on_noisy/output_dir_mlp_baseline_gpt2_arxiv_clean_on_noisy

dataset_name: ogbn-arxiv

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/no_robust_arxiv/output_dir_save_gpt2_noisy_arxiv_embedding_no_robust/gpt2_noisy_no_robust_arxiv_embedding.npy
# path_to_embeddings:

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 2
save_model_small: false
path_to_pretrained_classifier: /home/yourfirstname.yourlastname/experiment/classifier_with_standard/classifier_with_standard_gpt2_arxiv/model_checkpoints/classifier_with_standard_gpt2_arxiv.pth