absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/noisy_standard/output_dir_mlp_baseline_bert_products_noisy_standard_no_train

dataset_name: ogbn-products

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/save_noisy_standard_embeddings/bert_products_noisy_standard_embedding.npy

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 0
save_model_small: false
path_to_pretrained_classifier: /home/yourfirstname.yourlastname/experiment/classifier_with_standard/classifier_with_standard_bert_products/model_checkpoints/classifier_with_standard_bert_products.pth