absolute_path: /home/yourfirstname.yourlastname/experiment/distilbert_distillation_products/output_dir_distilbert_distillation_products_experiment
model_name: distilbert-base-uncased
dataset_name: ogbn-products
path_to_teacher_embedding: /home/yourfirstname.yourlastname/experiment/distilbert_distillation_products/output_dir_save_distilbert_distillation_products_embedding/distilbert_distillation_products_embedding.npy
min_layers: 1
max_layers: 9