absolute_path: /home/yourfirstname.yourlastname/experiment/distilbert_only_title/output_dir_distilbert_only_title_experiment
model_name: distilbert-base-uncased
dataset_name: ogbn-arxiv
only_title: True
path_to_teacher_embedding: /home/yourfirstname.yourlastname/experiment/distilbert_only_title/output_dir_save_distilbert_only_title_embedding/distilbert_only_title_embedding.npy
min_layers: 1
max_layers: 5