absolute_path: /home/yourfirstname.yourlastname/experiment/distilbert_only_title/output_dir_save_distilbert_only_title_embedding
use_lightning_checkpoint: false
lm_name: distilbert-base-uncased
dataset_name: ogbn-arxiv
only_title: True
device: cuda
path_to_model: /home/yourfirstname.yourlastname/experiment/distilbert_only_title/hyperparameter_tuning_distilbert_only_title/model_checkpoints/lr_6.010102448770004e-05
path_to_save_file: distilbert_only_title_embedding.npy