absolute_path: /home/yourfirstname.yourlastname/experiment/bert_only_title/output_dir_distill_embedding_bert_only_title
file_path: /home/yourfirstname.yourlastname/experiment/bert_only_title/output_dir_bert_only_title_experiment/model_checkpoints_test
