absolute_path: /home/yourfirstname.yourlastname/experiment/gpt2_distillation/output_dir_gpt2_distill
file_path: /home/yourfirstname.yourlastname/experiment/gpt2_distillation/output_dir_gpt2_experiment/model_checkpoints_test
model_name: gpt2