absolute_path: /home/yourfirstname.yourlastname/experiment/output_dir_distill_embeddings_for_layers_1_to_3
file_path: /home/yourfirstname.yourlastname/experiment/output_dir_distill_for_layers_1_to_3/model_checkpoints_test