absolute_path: /home/yourfirstname.yourlastname/experiment/bert_only_title/output_dir_bert_only_title_experiment
path_to_teacher_embedding: /home/yourfirstname.yourlastname/experiment/bert_only_title/output_dir_save_bert_only_labels_embedding/bert_only_title_embedding.npy
min_layers: 1
max_layers: 9
