# got 0.7138
# device: cuda
# path_to_model: /home/yourfirstname.yourlastname/experiment/output_dir_tune/model_checkpoints_test/lr_1.2452967354253948e-05
# path_to_save_file: /home/yourfirstname.yourlastname/experiment/output_dir/best_lm_lr_1.2452967354253948e-05.npy
device: mps
path_to_model: /Users/yourfirstnameyourlastname/Desktop/output_dir_tune/model_checkpoints_test/lr_1.2452967354253948e-05
path_to_save_file: ./my_test_save_embedding