absolute_path: /home/yourfirstname.yourlastname/experiment/output_dir_6_eps_test_distilbert
model_name: distilbert-base-uncased
path_to_pretrained_classifier: './saved/classifier_with_standard_bert.pth'
dropout_rate: 0.1
learning_rate: 0.00005
short_train: False
save_model: False
max_epoch: 6
custom_name: '6_eps_test_distilbert'