absolute_path: /home/yourfirstname.yourlastname/experiment/hyperparameter_tuning_gpt2
objective: 'objective1'
study_name: 'gpt2_study'
num_trials: 20
model_name: 'gpt2'

hyperparameters:
  path_to_pretrained_classifier:
    type: 'fixed'
    value: null
  dropout_rate:
    type: 'fixed'
    value: 0.1
  learning_rate:
    type: 'float'
    low: 1e-7
    high: 1e-2
    log: true
  max_epochs:
    type: 'fixed'
    value: 2
