absolute_path: /home/yourfirstname.yourlastname/experiment/hyperparameter_tuning_distilbert_products
objective: 'objective1'
study_name: 'my_study_distilbert_products'
num_trials: 10

model_name: distilbert-base-uncased
dataset_name: ogbn-products

hyperparameters:
  path_to_pretrained_classifier:
    type: 'fixed'
    value: './saved/classifier_with_standard_bert.pth'
  dropout_rate:
    type: 'fixed'
    value: 0.1
  learning_rate:
    type: 'float'
    low: 1e-6
    high: 1e-3
    log: true
  max_epochs:
    type: 'fixed'
    value: 1
