absolute_path: /home/yourfirstname.yourlastname/experiment/output_dir_hyperparameter_peft_bert
objective: 'objective3'
study_name: 'peft_bert_study'
num_trials: 25
model_name: bert-base-uncased

hyperparameters:
  rank:
    type: 'int'
    low: 4
    high: 64
  lora_alpha:
    type: 'int'
    low: 16
    high: 256
  dropout_rate:
    type: 'fixed'
    value: 0.1
  lora_dropout:
    type: 'float'
    low: 0.0
    high: 0.3
    log: false
  learning_rate:
    type: 'float'
    low: 1e-5
    high: 5e-4
    log: true
  weight_decay:
    type: 'float'
    low: 0.0
    high: 0.3
    log: false
  batch_size:
    type: 'categorical'
    choices: [4, 8, 16, 32]
  num_train_epochs:
    type: 'int'
    low: 1
    high: 3