absolute_path: /home/yourfirstname.yourlastname/experiment/tune_hyperparameters_mlp_standard_bert_embedding
objective: 'objective0'
study_name: 'mlp_standard_bert_embedding'
num_trials: 30

hyperparameters:
  different_embedding:
    type: 'fixed'
    value: './saved_embeddings/bert.npy'
  batch_size:
    type: 'categorical'
    choices: [8, 16, 32, 64, 128]
  learning_rate:
    type: 'float'
    low: 1e-5
    high: 1e-2
    log: true
  max_epoch:
    type: 'fixed'
    value: 30