objective: 'objective2'
study_name: 'graph_tune_study'
num_trials: 100

hyperparameters:
  num_layers: 
    type: 'fixed'
    value: 2
  hidden_channels:
    type: 'categorical'
    choices: [128, 256, 512]
  learning_rate:
    type: 'float'
    low: 1e-4
    high: 5e-3
    log: true
  weight_decay:
    type: 'loguniform'
    low: 1e-5
    high: 1e-2
  num_heads:
    type: 'fixed'
    value: 8
  batch_size:
    type: 'categorical'
    choices: [32, 64, 128, 256]
  dropout:
    type: 'loguniform'
    low: 0.3
    high: 0.6
  edge_dropout:
    type: 'loguniform'
    low: 0.3
    high: 0.6
  input_dropout:
    type: 'loguniform'
    low: 0.3
    high: 0.6
  label_smoothing:
    type: 'loguniform'
    low: 0.01
    high: 0.05
  input_norm:
    type: 'fixed'
    value: false