absolute_path: /home/yourfirstname.yourlastname/experiment/bert_noisy_no_robust/output_dir_save_bert_noisy_no_robust_embedding
use_lightning_checkpoint: false
lm_name: bert-base-uncased
dataset_name: ogbn-products
only_title: False
noisy: True
device: cuda
path_to_model: /Users/yourfirstnameyourlastname/Desktop/tune_hyperparameters_bert_products/model_checkpoints_test/lr_4.986838925488867e-05
path_to_save_file: bert_noisy_no_robust_products_embedding.npy