absolute_path: /home/yourfirstname.yourlastname/experiment/testing_results/testing_gpt2_products

model_name: gpt2
dataset_name: ogbn-products
only_title: false
noisy: false
custom_name: trained_gpt2_products_testing_performance
path_to_model: /home/yourfirstname.yourlastname/experiment/gpt2_distillation_products/tune_hyperparameters_gpt2_products/model_checkpoints/lr_0.0002187023895664096