absolute_path: /Users/yourfirstnameyourlastname/Desktop/experiment/mlp_baselines/output_dir_mlp_baseline_standard_bert_arxiv

dataset_name: ogbn-arxiv

path_to_original_embedding: /Users/yourfirstnameyourlastname/Desktop/output_dir_save_standard/output_dir_save_standard/output_dir_save_standard_bert_embedding/standard_bert_embedding.npy

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 3
save_model_small: false
path_to_pretrained_classifier: './saved/classifier_with_standard_bert.pth'