absolute_path: /home/yourfirstname.yourlastname/experiment/bert_noisy_arxiv/output_dir_train_robust_lm_bert_noisy_arxiv
model_name: bert-base-uncased
dataset_name: ogbn-arxiv
path_to_pretrained_classifier: ./saved/classifier_with_standard_bert.pth
dropout_rate: 0.1
learning_rate: 1.2452967354253948e-05
noisy: true
save_model_small: true
max_epoch: 2
custom_name: robust_bert-base-uncased_for_noisy_ogbn-arxiv_max_epoch_2