absolute_path: /Users/yourfirstnameyourlastname/Desktop/experiment/mlp_on_given_embedding/products
objective: 'objective0'
study_name: 'mlp_standard_given_embedding_products'
num_trials: 30

dataset_name: ogbn-products

hyperparameters:
  different_embedding:
    type: 'fixed'
    value: ~
  batch_size:
    type: 'categorical'
    choices: [8, 16, 32, 64, 128]
  learning_rate:
    type: 'float'
    low: 1e-5
    high: 1e-2
    log: true
  max_epoch:
    type: 'fixed'
    value: 30