absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/trained_on_clean_on_noisy/output_dir_mlp_baseline_bert_arxiv_clean_on_noisy

dataset_name: ogbn-arxiv

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/bert_noisy_no_robust/output_dir_save_bert_noisy_embedding/bert_noisy_embedding.npy
path_to_embeddings: /home/yourfirstname.yourlastname/experiment/bert_noisy_no_robust/output_dir_distill_embedding_bert_noisy

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 2
save_model_small: false
path_to_pretrained_classifier: './saved/classifier_with_standard_bert.pth'