absolute_path: /home/yourfirstname.yourlastname/experiment/mlp_baselines/noisy_standard/output_dir_mlp_baseline_distilbert_arxiv_noisy_standard_no_train

dataset_name: ogbn-arxiv

path_to_original_embedding: /home/yourfirstname.yourlastname/experiment/save_noisy_standard_embeddings/distilbert_arxiv_noisy_standard_embedding.npy
# path_to_embeddings: /home/yourfirstname.yourlastname/experiment/repeat_bert_distillation_for_all_layers/output_dir_distill_embedding_repeat_bert_distillation_for_all_layers

batch_size: 16
learning_rate: 1.2452967354253948e-05
max_epoch: 0
save_model_small: false
path_to_pretrained_classifier: './saved/classifier_with_standard_bert.pth'