absolute_path: /home/yourfirstname.yourlastname/experiment/gpt2_noisy_products/performance_on_clean_text/output_dir_distill_embedding_gpt2_noisy_products_clean
file_path: /home/yourfirstname.yourlastname/experiment/gpt2_noisy_products/output_dir_gpt2_noisy_products_experiment/model_checkpoints_test
model_name: gpt2
dataset_name: ogbn-products
only_title: False
noisy: False